/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>
/* Header for class CAOS */

#ifndef _Included_CAOS
#define _Included_CAOS
struct Hjava_awt_peer_ComponentPeer;
struct Hjava_awt_Container;
struct Hjava_awt_Color;
struct Hjava_awt_Font;
struct Hjava_awt_Cursor;
struct Hjava_util_Locale;
struct Hjava_util_Vector;
struct Hjava_lang_String;
struct Hjava_awt_Dimension;
struct Hjava_awt_event_ComponentListener;
struct Hjava_awt_event_FocusListener;
struct Hjava_awt_event_KeyListener;
struct Hjava_awt_event_MouseListener;
struct Hjava_awt_event_MouseMotionListener;
struct Hjava_awt_Component;
struct Hjava_awt_LayoutManager;
struct Hjava_awt_LightweightDispatcher;
struct Hjava_awt_event_ContainerListener;
struct Hjava_applet_AppletStub;
struct HmolPanel;
struct HtreePanel;
struct Hjava_awt_TextArea;
struct Hjava_awt_Button;

#pragma pack(4)

typedef struct ClassCAOS {
    struct Hjava_awt_peer_ComponentPeer *peer;
    struct Hjava_awt_Container *parent;
    long x;
    long y;
    long width;
    long height;
    struct Hjava_awt_Color *foreground;
    struct Hjava_awt_Color *background;
    struct Hjava_awt_Font *font;
    struct Hjava_awt_Cursor *cursor;
    struct Hjava_util_Locale *locale;
    /*boolean*/ long visible;
    /*boolean*/ long enabled;
    /*boolean*/ long valid;
    struct Hjava_util_Vector *popups;
    struct Hjava_lang_String *name;
    /*boolean*/ long nameExplicitlySet;
/* Inaccessible static: LOCK */
    struct Hjava_awt_Dimension *minSize;
    struct Hjava_awt_Dimension *prefSize;
    /*boolean*/ long newEventsOnly;
    struct Hjava_awt_event_ComponentListener *componentListener;
    struct Hjava_awt_event_FocusListener *focusListener;
    struct Hjava_awt_event_KeyListener *keyListener;
    struct Hjava_awt_event_MouseListener *mouseListener;
    struct Hjava_awt_event_MouseMotionListener *mouseMotionListener;
#undef CAOS_actionListenerK
#define CAOS_actionListenerK 706L
#undef CAOS_adjustmentListenerK
#define CAOS_adjustmentListenerK 716L
#undef CAOS_componentListenerK
#define CAOS_componentListenerK 730L
#undef CAOS_containerListenerK
#define CAOS_containerListenerK 739L
#undef CAOS_focusListenerK
#define CAOS_focusListenerK 765L
#undef CAOS_itemListenerK
#define CAOS_itemListenerK 821L
#undef CAOS_keyListenerK
#define CAOS_keyListenerK 876L
#undef CAOS_mouseListenerK
#define CAOS_mouseListenerK 901L
#undef CAOS_mouseMotionListenerK
#define CAOS_mouseMotionListenerK 904L
#undef CAOS_textListenerK
#define CAOS_textListenerK 977L
#undef CAOS_windowListenerK
#define CAOS_windowListenerK 990L
    int64_t eventMask;
/* Inaccessible static: isInc */
/* Inaccessible static: incRate */
#undef CAOS_TOP_ALIGNMENT
#define CAOS_TOP_ALIGNMENT 0f
#undef CAOS_CENTER_ALIGNMENT
#define CAOS_CENTER_ALIGNMENT 0.5f
#undef CAOS_BOTTOM_ALIGNMENT
#define CAOS_BOTTOM_ALIGNMENT 1f
#undef CAOS_LEFT_ALIGNMENT
#define CAOS_LEFT_ALIGNMENT 0f
#undef CAOS_RIGHT_ALIGNMENT
#define CAOS_RIGHT_ALIGNMENT 1f
#undef CAOS_serialVersionUID
#define CAOS_serialVersionUID -7644114512714619750LL
    long componentSerializedDataVersion;
    long ncomponents;
    struct HArrayOfObject *component;
    struct Hjava_awt_LayoutManager *layoutMgr;
    struct Hjava_awt_LightweightDispatcher *dispatcher;
    struct Hjava_awt_Dimension *maxSize;
    struct Hjava_awt_event_ContainerListener *containerListener;
#undef CAOS_serialVersionUID
#define CAOS_serialVersionUID 4613797578919906343LL
    long containerSerializedDataVersion;
/* Inaccessible static: panelLayout */
#undef CAOS_base
#define CAOS_base 73L
/* Inaccessible static: nameCounter */
#undef CAOS_serialVersionUID
#define CAOS_serialVersionUID -2728009084054400034LL
    struct Hjava_applet_AppletStub *stub;
    long PORT;
    struct Hjava_lang_String *fname;
    struct HmolPanel *pd;
    struct HtreePanel *pu;
    struct Hjava_awt_TextArea *text;
    struct Hjava_lang_String *s1;
    struct Hjava_lang_String *s2;
    long rxnnum;
    struct Hjava_awt_Button *upbutt;
    struct Hjava_awt_Button *downbutt;
    struct Hjava_awt_Button *casbutt;
    struct Hjava_awt_Button *infobutt;
    struct Hjava_awt_Button *helpbutt;
    struct Hjava_awt_Button *savebutt;
} ClassCAOS;
HandleTo(CAOS);

#pragma pack()

#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
